In [2]:
import numpy as np
ch_arr2=np.array(["apple","banana"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['apple', 'banana'], dtype='<U6')

In [3]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['apple', 'banana'], dtype='<U6')

In [4]:
array1=np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [5]:
array1.dtype

dtype('int32')

In [6]:
ch_arr2.dtype

dtype('<U6')

In [11]:
array8=np.array([1,2,3,4,5],dtype='i')

In [12]:
array8.dtype

dtype('int32')

In [18]:
array2connv=array8.astype('f')

In [21]:
array2connv

array([1., 2., 3., 4., 5.], dtype=float32)

In [20]:
char_conv=char_arr.astype('i')
char_conv

NameError: name 'char_arr' is not defined

In [22]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [24]:
ars2=np.zeros(4)
ars2

array([0., 0., 0., 0.])

In [25]:
ars3=np.random.random(4)
ars3

array([0.41852127, 0.28457196, 0.61960835, 0.43444104])

In [26]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [27]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
numsone1=np.zeros((3,2))
numsone1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
dimones=np.ones((4,3,2))
dimones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [30]:
dimones.ndim

3

In [32]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[1,2,3],[8,10,9]])

In [33]:
add=ar1+ar2
print("add:\n",add)

add:
 [[ 2  4  6]
 [12 15 15]]


In [35]:
sub=ar1-ar2
print("sub:\n",sub)

sub:
 [[ 0  0  0]
 [-4 -5 -3]]


In [36]:
div=ar1/ar2
print("div:\n",div)

div:
 [[1.         1.         1.        ]
 [0.5        0.5        0.66666667]]


In [37]:
power = np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1        4       27]
 [   65536  9765625 10077696]]


In [38]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,22,33])
sum=array2d+array1d
sum

array([[11, 24, 36],
       [14, 27, 39]])

In [39]:
range_arr=np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [41]:
w=np.random.randint(low=1,high=6,size=(2,3))
w

array([[5, 2, 5],
       [3, 5, 1]])

In [ ]:
import matplotlib.pyplot as plt
from scipy import stats

In [ ]:
exp = [1,2,3,4,5,6,7,8,9,10]
sal = [40,50,60,70,80,90,100,110,120,130]

In [ ]:
slope,intercept,r,p,std_err=stats.linregress(experience, salary)

In [ ]:
slope